[package]
name = "song-title"
version = "0.1.0"
edition = "2021"

[dependencies]
x11rb = { version = "0.13.1" }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
