[package]
name = "rpbar"
version = "0.1.0"
edition = "2021"

[dependencies]
x11rb = "0.13.1"
ureq = { version = "3.0.11", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }

[profile.release]
strip = true
lto = true
